### ISSUE TITLE
MudStepper IconButtons shown even if param false on navigation back 

### ISSUE THREAD

**Issue by PlayerModu** [CodeBeamOrg/CodeBeam.MudExtensions#171] opened 2023-04-06 19:11 UTC
If you set use icon buttons param to false, navigate forward a step and go then go back through the step(s), the buttons change to using the icons instead of the next/previous text?

**Comment by mckaragoz** [comment] 2023-04-08 10:17
Thats by design to gain more space, but after that `MobileView` and `IconActionButtons` parameters added, so we can discuss about design again.

**Comment by PlayerModu** [comment] 2023-04-08 11:23
It feels wrong for me to tell the component to not to use icons buttons but the component goes ahead and use them anyway? I'm not sure about the saving space design, it feels weird for the user to see text buttons saying previous/next and then see icons if they go back? At least from a consistency point of view for the user journey?

**Comment by TeaBreakTom** [comment] 2023-04-11 12:29
I've raised a PR which fixes this issue but otherwise keeps the existing functionality intact: https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/pull/173

**Comment by PlayerModu** [comment] 2023-04-12 07:57
I can confirm the PR raised by @TeaBreakTom has resolved this issue :)

**Comment by mckaragoz** [comment] 2023-04-12 07:58
It already released with 6.4.8 🙂 and thanks again @TeaBreakTom

**Closed as completed** 2023-04-12 09:25 UTC
