### ISSUE TITLE
 MudListExtended - Multiple values doesn't show Initiallly when Virtualize

### ISSUE THREAD

**Issue by segfault-** [CodeBeamOrg/CodeBeam.MudExtensions#203] opened 2023-05-06 15:14 UTC
MudListExtended, @bind-SelectedValues initially loading with 3 selected..... but only one selection is rendered..... if you use the scrollbar or type in the search filter then suddenly it renders correctly.  reproduced with :  https://try.mudblazor.com/snippet/cucxOyvMVJrhvQpK

**Comment by mckaragoz** [comment] 2023-05-07 20:46
Yes, it look like we have a bug with ItemCollection approach. Initial values works with RenderFragment approach
https://try.mudblazor.com/snippet/wucRazYhLerRJsIq

**Comment by mckaragoz** [comment] 2023-06-30 10:35
Update: It also works on ItemCollection, the problem is `Virtualize`

**Comment by segfault-** [comment] 2023-06-30 13:21
Ill link a try

**Comment by mckaragoz** [comment] 2023-07-07 18:38
This issue fixed with last release, thanks to @radderz again. We can close it now.

**Closed as completed by mckaragoz** 2023-07-07 18:38 UTC
Labels: bug
